#!/bin/bash
#SBATCH -J align_hisat2
#SBATCH -p Acluster
#SBATCH -n 8
#SBATCH --output=%align_hisat2.out
#SBATCH --error=%align_hisat2.err

mkdir 1.alignment_hisat2
for sample_name in VFUSI4dpi488-1 VFUSI4dpi488-2 VFUSI4dpi561-1 VFUSI4dpi561-2 VFUSI488-1 VFUSI488-2 VFUSI561-1 VFUSI561-2
do
	hisat2 -x /data/hisat2_mm10/mm10 \
		   -1 /data/00.CleanData/${sample_name}/${sample_name}_1.clean.fq.gz \
		   -2 /data/00.CleanData/${sample_name}/${sample_name}_2.clean.fq.gz \
		   -S /data/1.alignment_hisat2/${sample_name}.sam
done
